### ISSUE TITLE
Missing file for the Quick Example run

### ISSUE THREAD

**Issue by Leriabird** [LewisLabUCSD/GlyCompare#16]
'glytoucan_database.json' is not in the data package. I believe that causes 
```
Unexpected error: <class 'AssertionError'>
Traceback (most recent call last):
  File "/Users/Leria 1/Library/Mobile Documents/com~apple~CloudDocs/Documents/GlyCoCan_PhD/VU-code/test_glycompare_python_version.py", line 36, in <module>
    structure_loader=structure_loader)
  File "/usr/local/lib/python3.7/site-packages/glycompare-1.0.3-py3.7.egg/glycompare/pipeline_functions.py", line 243, in load_glycans_pip
AssertionError: missing glycan G79412GP
```

**Comment by bkellman** [comment]
Hi @Leriabird 
Very sorry for the late reply. I did not see this issue. The glytoucan_database file (glycompare/database/glytoucan_database.json) require lfs to download those larger files:
![image](https://github.com/LewisLabUCSD/GlyCompare/assets/5397154/601e8281-9643-48b7-a786-d8b9f9f76a35)

We had a lot of issues with the filesize and to mitigate these issues, we migrated to a less flexible but easier to use command line version: https://github.com/LewisLabUCSD/GlyCompareCT
The CT version includes some code memory optimization as well as precompiled executables.
